// flow-typed signature: 6d99cb970af98e39869b37bd21631753
// flow-typed version: <<STUB>>/react-native-music-control_v^0.4.13/flow_v0.60.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-music-control'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-music-control' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-music-control/index.android' {
  declare module.exports: any;
}

declare module 'react-native-music-control/index.ios' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-music-control/index.android.js' {
  declare module.exports: $Exports<'react-native-music-control/index.android'>;
}
declare module 'react-native-music-control/index.ios.js' {
  declare module.exports: $Exports<'react-native-music-control/index.ios'>;
}
